---
abstract: 'Generate random data structures'
author:
  - 'Mark Allen <mrallen1@yahoo.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Random-Structure
requires:
  Carp: 0
  Data::Random: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Data-Random-Structure
  homepage: https://metacpan.org/dist/Data-Random-Structure
  repository: git://github.com/mrallen1/WebService-Geocodio.git
version: 0.01
